### ISSUE TITLE
[BUG] Adding application to existing kubernetes cluster nothing happened

### ISSUE THREAD

**Issue by WillyRL** [civo/terraform-provider-civo#187] opened 2023-09-18 04:55 UTC
### Description

Hi There,
I just create my first kubernetes cluster on CIVO using civo terraform provider, but when i'm tried to update the cluster to add the `civo-cluster-autoscaler` nothing happened after terraform apply

```
applications = "civo-cluster-autoscaler"
```
After asking the same question on Civo Community Slack, @zulh-civo ask me to create the issue here.

Thanks !

**Comment by fernando-villalba** [comment] 2024-07-18 08:58
Duplicate of #258 We will be addressing this issue shortly. Thanks for reporting!

**Closed by fernando-villalba** 2024-07-18 08:58 UTC
Labels: bug
